### PR TITLE
Adding fignos-capitalise support.

### PR DESCRIPTION
**Pull request by shoeffner**
Since it took me a while to figure out why `capitalise` was not working properly I decided to add a similar meta variable to pandoc-fignos. I am aware that

```
fignos-capitalise: true
```

is basically equivalent to

```
fignos-plusname:
    - Fig.
    - Figs.
```

But I thought it might be more handy to have an option mimicking cleveref's capitalise.

What do you think? Is this a useful addition? Or should I better use `fignos-plusname`?

---------------

Adds support for the meta option fignos-capitalize/fignos-capitalise.
If turned on, the plusname values will be capitalized using .title().
This is done, because xnos does circumvent cleveref's "capitalise"
option by always setting [Cc]refformats. Citing from cleveref's
documentation:

> However, if you explicitly define a \cref variant to not be capitalised,
> cleveref will still honour your definition.

The behavior of this change is similar to cleveref's "capitalise"
option, see Section 7.1 of its documentation:
http://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/cleveref/cleveref.pdf

### CODE REVIEW

**Comment by tomduck** [comment]
This is nice.  Thank you for the contribution!  I'm going to see what can be done to get this into pandoc-eqnos and pandoc-tablenos as well, then push it out in a new release.

Note that I just made 1.0.0 official today.  I don't think that has any impact.

**Comment by tomduck** [comment]
I just put out a new release to address an earlier Issue.  This is next up.  There are some conflicts with the current release, but I don't think I will have trouble resolving them.

**Comment by tomduck** [comment]
I merged this into the `nextrelease` branch, which I use for development and testing.  I'm going to port these changes across to pandoc-eqnos and pandoc-tablenos as well, and include an `xnos-capitalise` flag (or some such thing) to turn all three on at once.

Thanks again for this contribution.

**Comment by tomduck** [comment]
This was just pushed out in pandoc-fignos 1.2.0.

I added you as a contributor in the AUTHORS file.  I trust that's OK.

I also added similar capabilities to pandoc-eqnos and pandoc-tablenos.

Cheers,
Tom

**Comment by shoeffner** [comment]
Thanks, that's great!

**Pull request merged**
